apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-task-platform
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- mongo-deployment.yaml
- mongo-service.yaml
- redis-deployment.yaml
- redis-service.yaml
- backend-deployment.yaml
- backend-service.yaml
- worker-deployment.yaml
- worker-hpa.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
images:
- name: YOUR_DOCKERHUB_USERNAME/ai-task-backend
  newName: ayush31082005/ai-task-backend
  newTag: b559f3b67cfd53fc1cca2e2e5bf7d8efd815e255
- name: YOUR_DOCKERHUB_USERNAME/ai-task-frontend
  newName: ayush31082005/ai-task-frontend
  newTag: b559f3b67cfd53fc1cca2e2e5bf7d8efd815e255
- name: YOUR_DOCKERHUB_USERNAME/ai-task-worker
  newName: ayush31082005/ai-task-worker
  newTag: b559f3b67cfd53fc1cca2e2e5bf7d8efd815e255
